knp_gaufrette:
  stream_wrapper: ~
  adapters:
    photo_url_adapter:
      aws_s3:
        service_id: reunion_file_store.s3
        bucket_name: '%env(AWS_BUCKET_NAME)%'
        detect_content_type: true
        options:
          create: true
          directory: photo_url
    reunion_photo_url_adapter:
      aws_s3:
        service_id: reunion_file_store.s3
        bucket_name: '%env(AWS_BUCKET_NAME)%'
        detect_content_type: true
        options:
          create: true
          directory: reunion_photo_url
  filesystems:
    photo_url_fs:
      adapter:    photo_url_adapter
    reunion_photo_url_fs:
      adapter:    reunion_photo_url_adapter