liip_imagine:
  loaders:
    default:
      filesystem:
        data_root:
          - '%kernel.project_dir%/public/images/reunion_photo_url'
          - '%kernel.project_dir%/public/images/photo_url'
        bundle_resources:
          enabled: true
  driver: "imagick"
  filter_sets:
    portrait_thumbnail:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [100, 115]
          mode:          outbound
          allow_upscale: true
    portrait_optimal:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [1024, 768]
          mode:          inset
          allow_upscale: true
    reunion_thumbnail:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [640, 180]
          mode:          outbound
          allow_upscale: true
    reunion_optimal:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [1024, 768]
          mode:          inset
          allow_upscale: true
