liip_imagine:
  loaders:
    reunion_photo_url_stream:
      stream:
        wrapper: gaufrette://reunion_photo_url_fs/
    photo_url_stream:
      stream:
        wrapper: gaufrette://photo_url_fs/
  driver: "imagick"
  filter_sets:
    portrait_thumbnail:
      data_loader: photo_url_stream
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [100, 115]
          mode:          outbound
          allow_upscale: true
    portrait_optimal:
      data_loader: photo_url_stream
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [1024, 768]
          mode:          inset
          allow_upscale: true
    reunion_thumbnail:
      data_loader: reunion_photo_url_stream
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [640, 180]
          mode:          outbound
          allow_upscale: true
    reunion_optimal:
      data_loader: reunion_photo_url_stream
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        auto_rotate: ~
        strip: ~
        thumbnail:
          size:          [1024, 768]
          mode:          inset
          allow_upscale: true
