twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: '%env(SITE_NAME)%'
        short_name: '%env(SHORT_NAME)%'
    form_themes: ['bootstrap_4_layout.html.twig']
