vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        reunion_photo_url:
            inject_on_load: true
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%/reunion_photo_url"
            upload_destination: reunion_photo_url_fs
            delete_on_update:   false
            delete_on_remove:   false
        photo_url:
            inject_on_load: true
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%/photo_url"
            upload_destination: photo_url_fs
            delete_on_update:   false
            delete_on_remove:   false