vich_uploader:
    db_driver: orm
    mappings:
        reunion_photo_url:
            inject_on_load: true
            uri_prefix: /images/reunion_photo_url
            upload_destination: '%kernel.project_dir%/public/images/reunion_photo_url'
            delete_on_update:   false
            delete_on_remove:   false
        photo_url:
            inject_on_load: true
            uri_prefix: /images/photo_url
            upload_destination: '%kernel.project_dir%/public/images/photo_url'
            delete_on_update:   false
            delete_on_remove:   false